### ISSUE TITLE
Pip package for latest release

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libCombine#36]
Would it be possible to proved pip releases for the latest python-libcombine & python-libsedml?

**Comment by fbergmann** [comment]
they pypi versions of libcombine and numl already had all recent changes. What changed since does not influence the python functionality at all. I just never tagged the repo here with a new release and was called out on that. that being said, i can release libnuml / combine so that the version numbers are consistent.

**Comment by fbergmann** [comment]
new wheels are now on pypi for libcombine and numl the sedml one is still up to date from last week.

**Comment by matthiaskoenig** [comment]
thanks Frank. Yes, would be great if the github release versions are in sync
